[package]
name = "tic-tac-toe_client"
version = "0.1.0"
edition = "2021"
authors = ["flofriday <flohacksfriday@gmail.com>", "nikos <nikos.terzo@mystenlabs.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.2.0"
